version: '3'
services:
  rest-resvice-api:
    container_name: rest-service
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres-rest-service
    build:
      context: .
      dockerfile: postgres.Dockerfile
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
volumes:
  pg_data:
